# Assignment 2(a)

In [1]:
import numpy as np

Q1

Create a 4 × 2 random integer array whose values can vary between 0 and 99. Print the following array attributes:

• The shape of the array

• Array dimensions

• The length of each element of the array in bytes

In [2]:
ranint_array = np.random.randint(0,100,size = (4,2))

In [3]:
[ranint_array, ranint_array.shape, ranint_array.ndim, ranint_array.itemsize]

[array([[68, 96],
        [56, 84],
        [56, 78],
        [69, 32]]),
 (4, 2),
 2,
 8]

Q2

Create a 5 × 2 integer array from a range between 100 to 200 such that the difference between each element is 10.

In [4]:
ranint_array2 = np.arange(100,200,10).reshape(5,2)
ranint_array2

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

Q3

Consider the following numPy array

import numpy as np

x = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

Return the array of elements in the third column (from all rows). 

Note that the third column is column 2 using Python zero indexing.

In [5]:
x = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
third_column_x = x[:,2]
third_column_x

array([33, 66, 99])

Q4

Consider the following numpy array

y = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

Return a sub-array consisting of the odd rows (rows 1, 3, ...) and even columns of y (columns 0, 2, ...) where odd and even uses Python zero indexing convention

In [6]:
y = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
y_sub = y[1::2,::2]
y_sub

array([[15, 21],
       [39, 45]])

Q5

(a) Input the following mathematical expressions into Python as NumPy arrays:

u = [ 1 1 2 3 5 8 ]

v = u'

x = [ 1 0 0 1 ]_2x2

y = [ 1 2 3 4 ]_2x2

z = [ 1 2 1 2 3 4 3 4 1 2 1 2 ]_3*4

w = [ x x y y ]_2x2

(b) What command would select x from w? (Hint: w[?,?] is the same as x.)

(c) What command would select [ x' y' ]' from w? (Where x' denotes the transpose of x.)

(d) What command would select y from z? List alternatives if you can.

In [7]:
u = np.array([1,1,2,3,5,8])
u

array([1, 1, 2, 3, 5, 8])

In [8]:
v = u.reshape(6,1)
v

array([[1],
       [1],
       [2],
       [3],
       [5],
       [8]])

In [9]:
x = np.eye(2)
x

array([[1., 0.],
       [0., 1.]])

In [10]:
y = np.arange(1,5).reshape(2,2)
y

array([[1, 2],
       [3, 4]])

In [11]:
z = np.vstack([y,y[0]])
z = np.hstack([z,z])
z

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2]])

In [12]:
w = np.concatenate([x,y])
w = np.concatenate([w,w],axis = 1)
w

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 2., 1., 2.],
       [3., 4., 3., 4.]])

In [13]:
w[0:2,0:2]

array([[1., 0.],
       [0., 1.]])

In [14]:
w[:,:2]

array([[1., 0.],
       [0., 1.],
       [1., 2.],
       [3., 4.]])

In [15]:
z[:2,:2]

array([[1, 2],
       [3, 4]])

In [16]:
z[:2,2:]

array([[1, 2],
       [3, 4]])

Q6

Set up an array x = [1,2,...,1000] and show that the following formula holds for N = 1000:

$ \sum\limits_{i = 1} ^{N} i = N*(N+1)/2$

In [17]:
def sum_integer_from_1_to_(N):
    return N*(N+1)/2

array_from_1_to_1000 = np.arange(1,1001)

np.sum(array_from_1_to_1000) == sum_integer_from_1_to_(1000)

True

Q7

Compute the cumulative sum in Problem 6 using (i) a for loop and (ii) NumPy’s cumsum function. 

Time both using %timeit and report your findings.

In [18]:
def csum_using_for(arr):
    '''cumulative sum of an array using for loop'''
    temp = 0
    for i in range(len(arr)):    
        arr[i] += temp
        temp = arr[i]        
    return arr

array_from_1_to_1000 = np.arange(1,1001)
csum_using_for(array_from_1_to_1000)

array([     1,      3,      6,     10,     15,     21,     28,     36,
           45,     55,     66,     78,     91,    105,    120,    136,
          153,    171,    190,    210,    231,    253,    276,    300,
          325,    351,    378,    406,    435,    465,    496,    528,
          561,    595,    630,    666,    703,    741,    780,    820,
          861,    903,    946,    990,   1035,   1081,   1128,   1176,
         1225,   1275,   1326,   1378,   1431,   1485,   1540,   1596,
         1653,   1711,   1770,   1830,   1891,   1953,   2016,   2080,
         2145,   2211,   2278,   2346,   2415,   2485,   2556,   2628,
         2701,   2775,   2850,   2926,   3003,   3081,   3160,   3240,
         3321,   3403,   3486,   3570,   3655,   3741,   3828,   3916,
         4005,   4095,   4186,   4278,   4371,   4465,   4560,   4656,
         4753,   4851,   4950,   5050,   5151,   5253,   5356,   5460,
         5565,   5671,   5778,   5886,   5995,   6105,   6216,   6328,
      

In [19]:
array_from_1_to_1000 = np.arange(1,1001)
%timeit csum_using_for(array_from_1_to_1000)

<ipython-input-18-115cf9c001c0>:5: RuntimeWarning: overflow encountered in long_scalars
  arr[i] += temp


829 µs ± 172 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [20]:
array_from_1_to_1000 = np.arange(1,1001)
np.cumsum(array_from_1_to_1000)

array([     1,      3,      6,     10,     15,     21,     28,     36,
           45,     55,     66,     78,     91,    105,    120,    136,
          153,    171,    190,    210,    231,    253,    276,    300,
          325,    351,    378,    406,    435,    465,    496,    528,
          561,    595,    630,    666,    703,    741,    780,    820,
          861,    903,    946,    990,   1035,   1081,   1128,   1176,
         1225,   1275,   1326,   1378,   1431,   1485,   1540,   1596,
         1653,   1711,   1770,   1830,   1891,   1953,   2016,   2080,
         2145,   2211,   2278,   2346,   2415,   2485,   2556,   2628,
         2701,   2775,   2850,   2926,   3003,   3081,   3160,   3240,
         3321,   3403,   3486,   3570,   3655,   3741,   3828,   3916,
         4005,   4095,   4186,   4278,   4371,   4465,   4560,   4656,
         4753,   4851,   4950,   5050,   5151,   5253,   5356,   5460,
         5565,   5671,   5778,   5886,   5995,   6105,   6216,   6328,
      

In [21]:
array_from_1_to_1000 = np.arange(1,1001)
%timeit np.cumsum(array_from_1_to_1000)

5.7 µs ± 577 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
