# Numpy Introduction

## A Python List Is More Than Just a List

The Python list contains a pointer to a block of pointers, each of which in turn points to a full Python object

In [1]:
range(10)

range(0, 10)

In [2]:
L = list(range(10))
L, type(L[0])

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], int)

In [3]:
L2 = [str(c) for c in L]
L2, type(L2[0])

(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], str)

Because of Python’s dynamic typing, we can even create heterogeneous lists:

In [4]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

## Creating Arrays

unlike Python lists, NumPy is constrained to arrays that all contain the same type

In [5]:
import numpy as np

In [6]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

If types do not match, NumPy will upcast if possible

In [7]:
# floating array
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

If we want to explicitly set the data type of the resulting array, we can use the dtype keyword

In [8]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [9]:
# nested lists result in multi-dimensional arrays 
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
# Starting at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# Create an array of 5 values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))

array([[0.48797805, 0.66409916, 0.66000526],
       [0.79447926, 0.89276383, 0.1503225 ],
       [0.03874198, 0.3168273 , 0.74881131]])

In [16]:
# Create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1 
np.random.normal(0, 1, (3, 3))

array([[ 1.41031372, -0.7718223 ,  1.03682779],
       [ 1.74248924,  0.0766771 , -0.45366935],
       [-0.65352978, -0.5017077 ,  1.79587651]])

In [17]:
# Create a 3x3 array of random integers in the interval [0, 10) 
np.random.randint(0, 10, (3, 3))

array([[1, 0, 7],
       [7, 0, 0],
       [1, 1, 9]])

In [18]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Create an uninitialized array of three integers # The values will be whatever happens to
# already exist at that memory location 
np.empty(3)

array([1., 1., 1.])

In [20]:
## NumPy Array Attributes

In [21]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # 1D array
x2 = np.random.randint(10, size=(3, 4)) # 2D array
x3 = np.random.randint(10, size=(3, 4, 5)) # 3D array
[x1,x2,x3]

[array([5, 0, 3, 3, 7, 9]),
 array([[3, 5, 2, 4],
        [7, 6, 8, 8],
        [1, 6, 7, 7]]),
 array([[[8, 1, 5, 9, 8],
         [9, 4, 3, 0, 3],
         [5, 0, 2, 3, 8],
         [1, 3, 3, 3, 7]],
 
        [[0, 1, 9, 9, 0],
         [4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1]],
 
        [[4, 9, 8, 1, 1],
         [7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4]]])]

In [22]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


In [23]:
print(x2[0]) # equivalent to x2[0, :]

[3 5 2 4]


In [24]:
## Array Indexing

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices

In [25]:
x = np.array([[3, 5, 2, 4],[7, 6, 8, 8],[1, 6, 7, 7]])
x[2,-1]

7

The NumPy slicing syntax follows that of the standard Python list; 

to access a slice of an array x, use this:

x[start:stop:step]

In [26]:
x = np.arange(10)
x[1::2]

array([1, 3, 5, 7, 9])

When the step value is negative, the defaults for start and stop are swapped

In [27]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
x[5::-2]

array([5, 3, 1])

array slices returns views rather than copies of the array data

in lists, slices will be copies

In [29]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy[0, 0] = 42
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

## Reshaping of arrays

In [30]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [32]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [33]:
x

array([1, 2, 3])

reshape( -1 ): numpy allow us to give one of new shape parameter as -1. It simply means that it is an unknown dimension and we want numpy to figure it out. 

In [45]:
grid = np.arange(1, 10).reshape((3, -1))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Concatenation of arrays

In [34]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [35]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [36]:
grid = np.array([[1, 2, 3],[4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [37]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [38]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],[6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [39]:
y = np.array([[99],[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [40]:
## Splitting of arrays

In [41]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [42]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[9 8 7]
 [6 5 4]]
[]


In [43]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[9 8]
 [6 5]]
[[7]
 [4]]
