# Data Manipulation with Pandas

## pd Series

In [1]:
import numpy as np
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [2]:
data.values,type(data.values)

(array([0.25, 0.5 , 0.75, 1.  ]), numpy.ndarray)

In [3]:
data.index

RangeIndex(start=0, stop=4, step=1)

while the Numpy Array has an implicitly defined integer index used to access the values, the Pandas Series has an explicitly defined index associated with the values

In [4]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [5]:
data['b']

0.5

In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [7]:
population_dict = {'California': 38332521,
                'Florida': 19552860,
                'Illinois': 12882135,
                'New York': 19651127,
                'Texas': 26448193}
population = pd.Series(population_dict)
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [8]:
population['California':'Illinois']

California    38332521
Florida       19552860
Illinois      12882135
dtype: int64

In [9]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [10]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [11]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [12]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

## pd DataFrame

If a Series is an analog of a one-dimensional array with flexible indices, a Dataframe is an analog of a two-dimensional array with both flexible row indices and flexible column names

In [13]:
area_dict = {'California': 423967, 'Florida': 170312,'Illinois': 149995, 'New York': 141297,'Texas': 695662}
area = pd.Series(area_dict)
area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
dtype: int64

In [14]:
states = pd.DataFrame({'area': area, 'pop': population})
states

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193

In [15]:
states.index, states.columns

(Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object'),
 Index(['area', 'pop'], dtype='object'))

Where a dictionary maps a key to a value, a Dataframe maps a column name to a Series of column data

In [16]:
states['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

## Constructing DataFrame objects

In [17]:
# From a single Series object
pd.DataFrame(population, columns=['population'])

population
California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193

In [18]:
# From a list of dicts
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [19]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [20]:
# From a dictionary of Series objects
pd.DataFrame({'area': area, 'population': population})

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [21]:
# From a two-dimensional NumPy array
pd.DataFrame(np.random.rand(3, 2),columns=['foo', 'bar'],index=['a', 'b', 'c'])

foo       bar
a  0.988533  0.783173
b  0.387716  0.154928
c  0.284170  0.079895

## pd index

In [22]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [23]:
indA = pd.Index([1, 3, 5, 7, 9]) 
indB = pd.Index([2, 3, 5, 7, 11]) 
print(indA & indB) # intersection
print(indA | indB) # union
print(indA ^ indB) # symmetric difference

Int64Index([3, 5, 7], dtype='int64')
Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')
Int64Index([1, 2, 9, 11], dtype='int64')


<ipython-input-23-b97d85a2dfbb>:3: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  print(indA & indB) # intersection
<ipython-input-23-b97d85a2dfbb>:4: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  print(indA | indB) # union
<ipython-input-23-b97d85a2dfbb>:5: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  print(indA ^ indB) # symmetric difference


## Series as dictionary

In [24]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],index=['a', 'b', 'c', 'd'])

In [25]:
data['b'],data['a':'c'],'a' in data,data.keys(),list(data.items())

(0.5,
 a    0.25
 b    0.50
 c    0.75
 dtype: float64,
 True,
 Index(['a', 'b', 'c', 'd'], dtype='object'),
 [('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)])

In [26]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [27]:
# masking
data[(data > 0.3) & (data < 0.8)],data[['a', 'e']]

(b    0.50
 c    0.75
 dtype: float64,
 a    0.25
 e    1.25
 dtype: float64)

In [28]:
#loc and iloc

Notice that when slicing with an explicit index (i.e.,data[‘a’ : ‘c’]), the final index is included in the slice, while when slicing with an implicit index (i.e., data[0 : 2]), the final index is excluded from the slice; it is recommended to use loc and iloc to make code easier to read and understand

In [29]:
data1 = pd.Series([0.25, 0.5, 0.75, 1.0],index=[1,2,3,4])

In [30]:
data1.loc[1:3]

1    0.25
2    0.50
3    0.75
dtype: float64

In [31]:
data1.iloc[1:3]

2    0.50
3    0.75
dtype: float64

## DataFrame as a Dictionary

In [32]:
area = pd.Series({'California': 423967, 'Florida': 170312,'Illinois': 149995, 'New York': 141297,'Texas': 695662})
pop = pd.Series({'California': 38332521, 'Florida': 19552860,'Illinois': 12882135, 'New York': 19651127,'Texas': 26448193})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193

In [33]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [34]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [35]:
data.values, type(data.values)

(array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
        [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
        [1.49995000e+05, 1.28821350e+07, 8.58837628e+01],
        [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
        [6.95662000e+05, 2.64481930e+07, 3.80187404e+01]]),
 numpy.ndarray)

In [36]:
data.T

California       Florida      Illinois      New York         Texas
area     4.239670e+05  1.703120e+05  1.499950e+05  1.412970e+05  6.956620e+05
pop      3.833252e+07  1.955286e+07  1.288214e+07  1.965113e+07  2.644819e+07
density  9.041393e+01  1.148061e+02  8.588376e+01  1.390767e+02  3.801874e+01

In [37]:
# passing a single index to an array accesses a row
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [38]:
# Passing a single “index” to a Dataframe accesses a column:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [39]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135

In [40]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135

In [41]:
data.loc[data.index[:3], :'pop']

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135

In [42]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
Florida   19552860  114.806121
New York  19651127  139.076746